# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    # Primero instalamos los requisitos de documentación
    - requirements: docs/requirements.txt
    # Luego instalamos el paquete en modo editable sin dependencias pesadas
    - method: pip
      path: .
      extra_requirements: []