# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11" # Usamos 3.11 para coincidir con tu entorno Debian actual

sphinx:
  configuration: docs/source/conf.py # Ajustado a tu ruta de archivos subidos

python:
  install:
    - method: pip
      path: . # Instala tu paquete usando el pyproject.toml
    - requirements: docs/requirements.txt # Para dependencias extra de Sphinx