# Read the Docs configuration file
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    # Instalamos solo lo necesario para generar los HTML
    - requirements: docs/requirements.txt